### ISSUE TITLE
Future Semester Ideas

### ISSUE THREAD

**Issue by rapheh** [Code4Community/mini-games#36]
## Cool future ideas
- Add laser sounds when shooting
- Add main menu
- Add bullet counter
- Add asteroids 
- Uses up bullet when wrong is answer
- Once out of bullets, lose game, reset score
- Have a score saved in a database with a scoreboard available??????
- Higher the score, harder the questions
- Different starting in main menu difficulties MAYBE??

**Comment by akundla** [comment]
all these have been made
